Update patch set 2
Patch Set 2:

got some compile error

target Java: CMParts (out/target/common/obj/APPS/CMParts_intermediates/classes)
packages/apps/CMParts/src/com/cyanogenmod/cmparts/activities/DisplayActivity.java:83: cannot find symbol
symbol  : variable mContext
location: class com.cyanogenmod.cmparts.activities.DisplayActivity
        int mElectronBeamAnimation = mContext.getResources().getBoolean(
                                     ^
packages/apps/CMParts/src/com/cyanogenmod/cmparts/activities/DisplayActivity.java:85: incompatible types
found   : int
required: boolean
        if (mElectronBeamAnimation) {
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
make: *** [out/target/common/obj/APPS/CMParts_intermediates/classes-full-debug.jar] Error 41
make: *** Waiting for unfinished jobs....

Patch-set: 2